### ISSUE TITLE
Canonical formatting

### ISSUE THREAD

**Issue by aquilax** [papatangosierra/serifu#2]
Hi, 
I spent some time today re-implementing the parser in go and was wondering if you have thought about a canonical formatting for the raw text format.

I've picked 4 space indent for panels and panel elements since that seems to be mostly used in the README but wanted to double check if you have any thoughts about it. 

Example:
https://github.com/aquilax/serifu-go/blob/11c7c7583ab4903410a56003b8e31075d681839f/example_test.go#L498-L581

**Comment by papatangosierra** [comment]
Wow! Hi! That is very impressive and cool—I've done almost no publicizing of this project yet, so I'm really curious to know how you ran across it! I'm very flattered. :)

As far as indentation goes, I did use four spaces for panels and lines in the examples, since I tend to think that makes individual pages and panels more easily visually distinguishable. However, in the editor I've been writing, I've ended up using glorified syntax highlighting to create "fake" indentation (see attached screenshot), again in an effort to improve script scan-ability. The text as pasted into that editor has no indentation at all.

<img width="697" alt="Screen Shot 2022-01-31 at 1 43 54 PM" src="https://user-images.githubusercontent.com/18516174/151870432-46814965-5325-4a25-a80d-4a3c2e006b81.png">

I don't have strong feelings on what's considered correct, since Serifu is meant to be as un-opinionated as possible while still being rigorously parseable. A "correct" parse of the language will reliably ignore whitespace before the token that denominates a given line type.

I can say that in usage examples, I will probably continue to indent as I have been, or I may move the examples to one indent level for panel markers and two for lines, contingent on the feedback of beta testers.

**Comment by aquilax** [comment]
Thank you for your reply. 

I saw the project featured here: https://joy.recurse.com/posts/1408-serifu-a-markup-language-for-comic-book-scripts

Excellent work on the editor. I especially liked the color coding for each character.  

As for the text representation, I will leave it as it is for now and will keep an eye on the repository for updates.
